### ISSUE TITLE
Blocking googleusercontent.com breaks videos on certain websites

### ISSUE THREAD

**Issue by uBlock-user** [disconnectme/disconnect-tracking-protection#113]
Level 2 category of Disconnect.me breaks videos hosted on googleusercontent.com on websites such kissanime.ac/ru, animehub.ac. etc, please remove googleusercontent.com from the list.

@patjack Currently I'm able to reproduce this in Firefox 72

Testurl -- https://kissanime.ac/Anime/Fairy-Tail.78285/Episode-013?id=828&s=ptserver

**Comment by englehardt** [comment]
To report Firefox breakage you can also file the bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1400025 (for video related breakage).

**Comment by uBlock-user** [comment]
@englehardt Is that required ? Can you not just remove googleusercontent.com from the list ? 

Strange thing is this started happening on Nightly only sicne the past 2 days, and I haven't updated Nightly in 7 days, so what is it ?

**Comment by englehardt** [comment]
@uBlock-user From your description it sounds like you have tracking content blocked with the Level 2 blocklist. You'd have to be in the "Custom" mode of the ETP settings in `about:preferences#privacy`, and have manually changed the blocklist to Level 2 using the "Change block list" setting. Is that correct?

I suspect Disconnect won't change the domains on the list (though that's entirely their decision). The Level 2 blocklist is known to introduce site breakage when tracking content is blocked, which is why we've included the "Some websites or content may not load properly" warning in the panel that allows you to activate the Level 2 list.

**Comment by uBlock-user** [comment]
> From your description it sounds like you have tracking content blocked with the Level 2 blocklist. You'd have to be in the "Custom" mode of the ETP settings in about:preferences#privacy, and have manually changed the blocklist to Level 2 using the "Change block list" setting. Is that correct?

Yes. So I have to live with the breakage ?

**Comment by uBlock-user** [comment]
Fixed. Issue with the Nightly. Disabled uBlock Origin, clear cache and site data, set Tracking Protection to level 2, tested, it worked. Restarted the browser, enabled uBlock Origin and now back to old behaviour. Seems it was a race condition of sorts.
