### ISSUE TITLE
adform.com domain is mistakenly included in tracking protection

### ISSUE THREAD

**Issue by aidasg** [disconnectme/disconnect-tracking-protection#117]
By design Adform has specific "adform.net" domain dedicated for tracking and "adform.com" is used only for Adform Advertising platform usage. Having it included in tracking protection potentially will harm third-party integrations and platform behavior by blocking interaction with this domain. In order to mitigate upcomming issues "adform.com" domain needs to be removed from the entities and services list.

There are pull requests issued for this case: 
* https://github.com/disconnectme/disconnect-tracking-protection/pull/110
* https://github.com/disconnectme/disconnect-tracking-protection/pull/111

**Comment by disconnectme** [comment]
Adform's privacy policy indicates proper classification. For example:

"What Information Do We Collect and Use

When we refer to the term "Information", we mean data that is generated through the Service as well as data that our clients and partners receive from other sources and use in our Service as described in further detail below. For some of the Information, Adform is legally responsible for the use of the data with respect to privacy regulation – in legal terms it acts as a Controller. Other parts of the Information are processed by Adform on behalf of its clients, and Adform is bound by the instructions of its clients when processing such data. This Privacy Policy describes how Information controlled by Adform is used within the Service. While this Privacy Policy may also explain how Adform enables its clients to use their Information within the Service, it does not otherwise apply to the use of Information by our clients or other third parties outside of the Services. 

In order to operate the Service, Adform may collect and use the following Information:

Cookie ID  
In order to link each single interaction to an individual device, Adform generates a unique device ID for every new device which interacts with any form of Adform advertisements or website tracking. The unique device ID is stored locally by using a Cookie in the user’s browser. The Cookie, by default, expires 60 days after the last interaction. The device ID is either generated as a truly random number or in some cases combined with an ID generated by static and dynamic variables from the browser and device configuration.  

Mobile Advertising ID 
The Mobile Advertising ID is the technical ID in Mobile App Environments, e.g., on smartphone operating systems like Android and Apple IOS, that is under full control of the user and owner of that device and that can be reset by the user. 
Cross-Device IDs 
This ID is a user ID generated by Adform by using statistical and probabilistic algorithms in an attempt to link devices and identifiers belonging to the same user. Adform generates and purchases 3rd party Cross-Device IDs for the purposes described in further detail below.  
Partner IDs 
Adform is connected to a large number of partners such as Google, Adobe, Oracle, Amazon, and many others. In order to enable the provisioning of our services in the cookie-based advertising ecosystem, Adform automatically exchanges pseudonymous IDs with such partners. These IDs are strictly pseudonymous on both sides. ID synchronization is an essential prerequisite for the provision of the Service.  
Adform also collects and stores certain Information for its clients related to the interaction that users have with ads and digital properties such as websites or mobile apps: 

The type of browser used by a user, and its settings. 
Information about the device operating system. 
Information about Cookie IDs and other IDs assigned to a device. 
IP addresses from which a device interacts with a client´s website or mobile application; IP addresses may be truncated or encrypted or both based on local legislation or other requirements.  
Information about a user's interaction and activity on web pages and mobile apps, including time of the interaction or activity, the internet addresses involved, and search terms entered into a search engine. 
Information about the approximate geographic location (city, region, zip code) of the device when it accesses a website or mobile app derived from truncated IP address information or truncated GPS data."
