### ISSUE TITLE
Consider removing GTM / Google Tag Manager as a tracker

### ISSUE THREAD

**Issue by cosminstefanxp** [disconnectme/disconnect-tracking-protection#166]
I would like to propose the removal of Google Tag Manager as a tracker.

It's not doing tracking anything by itself. It's a tool for managing different JS based tools. If the tracking tools themselves are blocked (e.g. Google Analytics or Facebook Pixel), there's no reason to block Google Tag Manager.

My feeling is that this hurts the environment a lot. For example, via GTM, some websites might provide support features, based on user actions. This is not tracking in any way and the user ends up being hurt by this.

Another example is: https://github.com/mozilla-services/shavar-prod-lists/issues/46, where GCP stackdriver console is broken due to this. 

Further examples of situations where GTM would be beneficial:
- adding support tools for users, depending on the place they are in the app (e.g. the "it seems you're stuck on this. Do you need help?";
- monitoring of performance of remote dependencies;
- consoles (such as GCP's);

Furthermore, Google has made it clear that they are not persisting or using any tracking data in their [policy](https://support.google.com/tagmanager/answer/9323295#data).

**Comment by disconnectme** [comment]
Google Tag Manager was removed on April 25, 2019. https://github.com/disconnectme/disconnect-tracking-protection/commit/ac72379301ae4528f83e2110546b18e1d08d80d2#diff-f5fb0346ca2de022483b15e81d888f18

Google Tag Manager updated it’s public policy to make clear it does not engage in tracking as defined by Disconnect. Specifically they state: "In order to monitor system stability and performance, Google Tag Manager may collect some aggregated data about tag firing. This data does not include user IP addresses or any user-specific identifiers that could be associated with a particular individual. Other than data in standard HTTP request logs, all of which is deleted within 14 days of being received, Google Tag Manager does not collect, retain, or share any information about visitors to our customers’ properties, including page URLs visited.” https://support.google.com/tagmanager/answer/9323295#data
