### ISSUE TITLE
Consider moving ebayimg.com to the Content category

### ISSUE THREAD

**Issue by englehardt** [disconnectme/disconnect-tracking-protection#225]
`ebayimg.com` is currently in the advertising category. Blocking this domain causes breakage in Firefox (see [Bug 1656968](https://bugzilla.mozilla.org/show_bug.cgi?id=1656968)). 

When no tracking protection is applied, I see that requests to the domain (at least on https://www.gumtree.com.au/) don't include cookies. I also don't see any site data or cookies set under that domain in Firefox.

**Comment by disconnectme** [comment]
Since ebayimg.com does not appear in a third-party context very often, the vast majority of breakage issues, especially with default privacy settings, should be resolved by adding the Ebay first party domains to the entity list, which we have done here [65f3f14](https://github.com/disconnectme/disconnect-tracking-protection/commit/65f3f14945dd43c92952569fee1185d301e2a20e#diff-945c4feba40be6bc42659b8a2421c0ce).

Ebay policy and technical analysis indicates proper classification of this domain. Ebay allows for third party collection (and indefinite retention) of a wide range of data regarding particular users and devices, “including your general location data (e.g., IP address) and the precise location data of your mobile device . . .  Computer and connection information, such as statistics regarding your use of services from eBay, information on data traffic to and from websites, referral URL, information on advertisements, your IP address, your access times, your browser history data, your language settings and your weblog information.”

At this time, ebayimg.com will remain in the advertising category, however please keep us posted on future breakage or usability issues.
