### ISSUE TITLE
ondemand.com unclear why on the list

### ISSUE THREAD

**Issue by clnative** [disconnectme/disconnect-tracking-protection#355]
### Domain(s) to review. Separate them by comma.

ondemand.com

### Rationale for removing, adding, or recategorizing.

*so far: request for information only*

### Additional notes

`ondemand.com` is a generic domain for a large set of services both operated by SAP and non-SAP. It remains unclear, why the domain (in such generality) is on the list in first place. 

* The entry was added with 44fceba8494af171ef0f7fefa002d27e2de5a78a. The commit message does not provide any reason.
* Up to c8cc2e4850a01609d2f819181350da78b24decb7 there was a description available why the domain *was* on the list. However, the reason provided there was no longer valid latest by August 2023. 
* Yet, `ondemand.com` was not removed from `services.json`.

Please provide a reason (in `description.md`) why `ondemand.com` still is on the list. If there is no such reason, please remove the domain from the list.

**Comment by disconnectme** [comment]
Thank you for bringing this to our attention. Our technical and policy review determined that [ondemand.com](http://ondemand.com/) meets our definition of Tracking (See https://disconnect.me/trackerprotection), and that this domain is properly classified.
 
Our technical review revealed Request URLs from [ondemand.com](http://ondemand.com/) subdomains are present in emails. We are seeing what appear to be tracking requests (containing information “pixel.gif”) from subdomains including but not limited to the following:
- Request URL: https://smc-link.s4hana.ondemand.com/na/data-buffer/sap/public/cuan/link/100/CCA86B09EFDAF4D53FF3A12BDC04843F90402EE8/pixel.gif?_L54AD1F204_=c2NlbmFyaW89TUxPUEVOJnRlbmFudD1teTMwNDUzNS5zNGhhbmEub25kZW1hbmQuY29t 
- Request URL: https://smc-link.s4hana.ondemand.com/na/data-buffer/sap/public/cuan/link/100/A4E276F356330493333D5CC07CAA33D53FD265F6/pixel.gif?_L54AD1F204_=c2NlbmFyaW89TUxPUEVOJnRlbmFudD1teTMwNDUzNS5zNGhhbmEub25kZW1hbmQuY29t 
 
In addition, several portions of the SAP policy and website marketing seem to support the current classification, including but not limited to the following:
 
Website marketing:
- “Execute customer engagement campaigns across multiple channels and deliver consistent, relevant messaging across e-mail, web, mobile, ads, and more.” https://www.sap.com/products/crm/customer-engagement-platform.html 
- “Deliver consistent, relevant messaging across e-mail, web, mobile, ads, and more — engaging customers wherever they are.” https://www.sap.com/documents/2021/10/a239e08e-047e-0010-bca6-c68f7e60039b.html 
- “Automate campaigns and execute on a global scale. Customer engagement solutions from SAP help you identify target audiences, deliver personalized omnichannel experiences, and measure your results.” https://www.sap.com/products/crm.html 
- “Since implementing the solutions, Ferrara has seen open rates for e-mail campaigns of between 20% and 30%, which is 10% to 20% above the industry average. And using the solutions helps ensure Ferrara engages with consumers in a way that respects consumer privacy laws. The company is also conducting A/B test personalization within the subject and body of the e-mails to gauge the benefits of personalization in terms of more consumer engagement.” https://www.sap.com/about/customer-stories/ferrara-crm.html 
 
Privacy policy https://www.sap.com/about/legal/privacy.html talks about data collection:
- “Data generated through your use of, or participation in SAP's internet pages, web, or online offerings: Usage data: SAP processes certain user-related information, e.g., info regarding your browser, operating system, or your IP address when you visit SAP’s web properties. We also process information regarding your use of our web offerings, like the pages you visit, the amount of time you spend on a page, the page which has referred you to our page and the links on our sites you select.”
- “SAP may collect various types of personal data about you when conducting its business, including:
* personal contact data,
* personal data related to your or your employer’s business relationship with SAP,
* personal data SAP must collect due to legal- and compliance-related purposes,
* personal usage, registration, and participation data which SAP may generate through your use of its web and online offerings,
* special categories of personal data,
* application-related personal data,
* personal data which SAP may receive from third parties,
* personal data SAP requires to ensure your or your employer’s satisfaction with our products, services and offerings.”
- “SAP processes your personal data to:
* pursue its business relationships with you, your employer, or your employer’s customers, including ensuring your satisfaction with and keeping you up to date on the latest news about our products and services,
* develop and offer you its software products, cloud, and other services,
* protect the quality and safety of its premises, facilities, products, or services,
* secure and, if necessary, defend its protected legal assets against unlawful attacks, assert our rights or defend SAP against legal claims,
* ensure compliance with statutory laws and regulations applicable to SAP,
* operate SAP’s Internet pages, web offerings, or other online events including analyzing the behavior of the users, enabling you to create a user profile, benefit from an identity service and to promote and continuously improve your user experience,
* search you as a potential talent for SAP,
* transfer it to recipients like other entities of the SAP Group, third-party service providers, SAP partners and others.”
- “SAP may retain your personal data for additional periods if necessary for compliance with legal obligations to process your personal data or if the personal data is needed by SAP to assert or defend itself against legal claims. SAP will retain your personal data until the end of the relevant retention period or until the claims in question have been settled.”

Regarding the SAP entry that was previously on descriptions.md, those descriptions are for domains we categorize as Fingerprinters. The [ondemand.com](http://ondemand.com/) domain is included in our Email category not FingerprintingGeneral or FingerprintingInvasive and would not have an entry on the descriptions.md page as a result. 

Based on this analysis we believe this domain is properly classified.
