### ISSUE TITLE
Use fully-qualified domain names for Yandex instead of yandex.ru

### ISSUE THREAD

**Issue by groovecoder** [disconnectme/disconnect-tracking-protection#39]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1432650 ...

`yandex.ru` appears in the "Advertising" section, which means all of its subdomains (like api-maps.yandex.ru) are blocked. But `api-maps.yandex.ru` is categorized as "Content".

Can we adjust the yandex entries in "Advertising" to use the fully-qualified domain names of the advertising Yandex domains, so that other non-advertising Yandex domains will be allowed?

**Comment by recockerell** [comment]
I I am Rachael Cockerell and I am not sending you these emails to
disconnect or verify  anything. My accounnt hgas been hacked

**Comment by carbureted** [comment]
We should be able to do this, though it depends on whether or not yandex.ru itself is used as a tracking domain (I vaguely recall it being one the last time we looked at them). I'm gathering some data now so we can make an informed decision.

**Comment by carbureted** [comment]
It looks like Yandex uses a couple domains for third-party behavior, including yandex.ru itself. The biggest offender subdomains appear to be `an.yandex.ru`, `adfox.yandex.ru`, `awaps.yandex.ru`, and `mc.yandex.ru`.

The resources that show up on third party sites from the the plain yandex.ru domain are below. They look like tracking resources to me - I'll confirm with Yandex but building the case for a whitelist might be difficult. Because most tracking seems to come from yandex subdomains it's possible that we make the tradeoff and unblock the root domain, but it looks like there's definitely tracking coming from the root yandex domain.

yandex.ru/cycounter
yandex.ru/clck/click
yandex.ru/clck/counter
yandex.ru/set/s/rsya-tag-users/data
yandex.ru/portal/set/any

**Comment by fmarier** [comment]
In Firefox, we are not limited to domains, so we could add these five URL prefixes and remove `yandex.ru` from the list:

- `yandex.ru/cycounter`
- `yandex.ru/clck/click`
- `yandex.ru/clck/counter`
- `yandex.ru/set/s/rsya-tag-users/data`
- `yandex.ru/portal/set/any`

I imagine that might be a problem for other Disconnect products though?

**Comment by carbureted** [comment]
Interesting. That wouldn't work for other Disconnect projects but it's potentially a solution if we can't figure anything else out.

**Comment by renispring** [comment]
Hi, everyone!
What are the expectations on the fix release?

**Comment by groovecoder** [comment]
We just had another bugzilla comment/ping from this: https://bugzilla.mozilla.org/show_bug.cgi?id=1432650#c7

**Comment by renispring** [comment]
Guys, it's been half a year since we reported the issue for the first time. Thousands of web-sites are affected but unfortunately, we don't get any feedback or plans to fix the isssue. 
Am I right that our only option is to recommend users to disable tracking protection or use some other web-browsers? Is there any other workaround?

**Comment by fmarier** [comment]
> Is there any other workaround?

Here's a concrete solution that could be implemented server-side on the Yandex side:

1. Create a new subdomain for any tracking-related scripts (e.g. `counter.yandex.ru` or `analytics.yandex.ru`).
2. Host **all** of the tracking scripts there:
    - `analytics.yandex.ru/cycounter`
    - `analytics.yandex.ru/clck/click`
    - `analytics.yandex.ru/clck/counter`
    - `analytics.yandex.ru/set/s/rsya-tag-users/data`
    - `analytics.yandex.ru/portal/set/any`
    - ...
3. Redirect the existing URLs to the new subdomain (as a `301` HTTP response):
    - `yandex.ru/cycounter` => `analytics.yandex.ru/cycounter`
    - `yandex.ru/clck/click` => `analytics.yandex.ru/clck/click`
    - ...
4. Don't add any more tracking scripts directly to the `yandex.ru` domain and add them to `analytics.yandex.ru` instead.

Once that's in place, we can remove `yandex.ru` from the list and replace it with `analytics.yandex.ru`. That will prevent any of Yandex's subdomains from being blocked (e.g. the maps), without requiring users of your tracking/analytics services to change anything on their end.

**Comment by renispring** [comment]
Unfortunately that's not an option and we still look forward for the proper solution from your side.

**Comment by renispring** [comment]
Hi everyone, we discovered that our payment service located on trust.yandex.ru is also affected. Please note that this service doesn't use any counters at all and anyway is blocked together with yandex.ru. 
As speaking of Maps API we don't gather any personal data as well and use counters only to collect technical statistics e.g. crashes, modules/controls usage or performance metrics. 

So, as far as I see the case you already allowed all of this counters on Yandex own domains but block all Yandex services on 3rd-party domains. At the same time services used on 3rd party domains and requested from yandex.ru aren't used for tracking. I belive you already have no blockers to remove yandex.ru from the list and replace it with subdomains listed in above comments (e.g. mc.yandex.ru)

**Comment by spijet** [comment]
Having `yandex.ru` even in the Basic tracking list (as opposed to full blocklist) breaks a lot of different websites in Russia (e.g. real estate search websites and online banking), making them unusable until the user disables Firefox's Tracking Protection altogether.

In my case, I use Fx's container tabs to isolate websites with embedded Yandex services and turn TP off for them, to limit any possible exposure, but this requires some manual intervention and is not a viable strategy for ordinary users.

@renispring, why isn't moving all tracking-related features to a different 3rd level domain an option? Just curious.

**Comment by renispring** [comment]
Most of mentioned endpoints aren't even used in API, those used in API aren't used for tracking. Also Disconnect already allowed usage of this services on Yandex' own web pages and only blocks API on 3rd party domains. 
**There are no real blockers to remove yandex.ru from blocklist.**

Moving everything to a different domain requires lots of maintenance of all Yandex services (where tracking already allowed) including deprecated ones and can't be done only on API side (the only blocked service). Even with simple redirect it doesn't sound reasonable in any way.

**Comment by renispring** [comment]
Hi everyone!
It's been almost a year since bug report and now we have complaints from Samsung Internet users regarding the same issue. Is there any chance it would be fixed?

[Here ](https://bugzilla.mozilla.org/show_bug.cgi?id=1432650) colleagues from Mozilla agreed to make a patch on their own side and need only list of paths to be treated as analytics (so they could allow all other requests). Could you kindly provide such a list?

**Comment by disconnectus** [comment]
Resolved.
